### ISSUE TITLE
Improved Path-Matcher

### ISSUE THREAD

**Issue by Basicprogrammer10** [Basicprogrammer10/afire#22]
Progress [here](https://gist.github.com/Basicprogrammer10/0a864c0511b02ad2fc922e1fb0cf142f)

```rust
mango/{file}.{ext}

match char {
    '/' => // push
    '{' => // push & open
    '}' => // close
    _   => // buff push
}
```

**Comment by connorslade** [comment]
Fixed in 94c2156cbc214d0e2e7cbbd86e550d6966dffd1c.
Only took 6 months :3
well only 2 days after actually starting
